INSERT INTO books (title, author, release_date, stock) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 1967, 5);
INSERT INTO books (title, author, release_date, stock) VALUES ('Orgullo y prejuicio', 'Jane Austen', 1813, 12);
INSERT INTO books (title, author, release_date, stock) VALUES ('1984', 'George Orwell', 1949, 8);
INSERT INTO books (title, author, release_date, stock) VALUES ('Matar a un ruiseñor', 'Harper Lee', 1960, 7);
INSERT INTO books (title, author, release_date, stock) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', 1605, 14);
INSERT INTO books (title, author, release_date, stock) VALUES ('Harry Potter y la piedra filosofal', 'J.K. Rowling', 1997, 20);
INSERT INTO books (title, author, release_date, stock) VALUES ('La Odisea', 'Homero', -800, 10);
INSERT INTO books (title, author, release_date, stock) VALUES ('Crónica de una muerte anunciada', 'Gabriel García Márquez', 1981, 6);
INSERT INTO books (title, author, release_date, stock) VALUES ('Moby Dick', 'Herman Melville', 1851, 9);
INSERT INTO books (title, author, release_date, stock) VALUES ('Los juegos del hambre', 'Suzanne Collins', 2008, 15);
INSERT INTO books (title, author, release_date, stock) VALUES ('Ulises', 'James Joyce', 1922, 11);
INSERT INTO books (title, author, release_date, stock) VALUES ('El gran Gatsby', 'F. Scott Fitzgerald', 1925, 13);
INSERT INTO books (title, author, release_date, stock) VALUES ('Anna Karenina', 'León Tolstói', 1877, 16);
INSERT INTO books (title, author, release_date, stock) VALUES ('Sapiens: De animales a dioses', 'Yuval Noah Harari', 2011, 22);
INSERT INTO books (title, author, release_date, stock) VALUES ('Los pilares de la Tierra', 'Ken Follett', 1989, 18);
INSERT INTO books (title, author, release_date, stock) VALUES ('Lo que el viento se llevó', 'Margaret Mitchell', 1936, 9);
INSERT INTO books (title, author, release_date, stock) VALUES ('Bartleby, el escribiente', 'Herman Melville', 1853, 5);
INSERT INTO books (title, author, release_date, stock) VALUES ('Benito Cereno', 'Herman Melville', 1855, 4);
INSERT INTO books (title, author, release_date, stock) VALUES ('Billy Budd', 'Herman Melville', 1924, 6);
INSERT INTO books (title, author, release_date, stock) VALUES ('La Encantadora', 'Herman Melville', 1856, 3);
INSERT INTO books (title, author, release_date, stock) VALUES ('Redburn', 'Herman Melville', 1849, 5);
INSERT INTO books (title, author, release_date, stock) VALUES ('Israel Potter', 'Herman Melville', 1855, 4);
INSERT INTO books (title, author, release_date, stock) VALUES ('Pierre o las ambigüedades', 'Herman Melville', 1852, 7);
INSERT INTO books (title, author, release_date, stock) VALUES ('El guardián entre el centeno', 'J.D. Salinger', 1951, 7);
INSERT INTO books (title, author, release_date, stock) VALUES ('El código Da Vinci', 'Dan Brown', 2003, 14);
INSERT INTO books (title, author, release_date, stock) VALUES ('La metamorfosis', 'Franz Kafka', 1915, 5);
INSERT INTO books (title, author, release_date, stock) VALUES ('El nombre de la rosa', 'Umberto Eco', 1980, 10);
INSERT INTO books (title, author, release_date, stock) VALUES ('El lobo estepario', 'Herman Hesse', 1927, 8);
INSERT INTO books (title, author, release_date, stock) VALUES ('Sidharta', 'Herman Hesse', 1922, 7);
INSERT INTO books (title, author, release_date, stock) VALUES ('Bajo las ruedas', 'Herman Hesse', 1906, 5);
INSERT INTO books (title, author, release_date, stock) VALUES ('Demian', 'Herman Hesse', 1919, 6);
INSERT INTO books (title, author, release_date, stock) VALUES ('El juego de los abalorios', 'Herman Hesse', 1943, 4);
INSERT INTO books (title, author, release_date, stock) VALUES ('Narciso y Goldmundo', 'Herman Hesse', 1930, 6);
INSERT INTO books (title, author, release_date, stock) VALUES ('Mujercitas', 'Louisa May Alcott', 1868, 8);
INSERT INTO books (title, author, release_date, stock) VALUES ('La iliada', 'Homero', -750, 12);
INSERT INTO books (title, author, release_date, stock) VALUES ('El laberinto de los espíritus', 'Carlos Ruiz Zafón', 2016, 11);
INSERT INTO books (title, author, release_date, stock) VALUES ('Drácula', 'Bram Stoker', 1897, 7);
INSERT INTO books (title, author, release_date, stock) VALUES ('La sombra del viento', 'Carlos Ruiz Zafón', 2001, 9);
INSERT INTO books (title, author, release_date, stock) VALUES ('La naranja mecánica', 'Anthony Burgess', 1962, 7);
INSERT INTO books (title, author, release_date, stock) VALUES ('La catedral del mar', 'Ildefonso Falcones', 2006, 10);
INSERT INTO books (title, author, release_date, stock) VALUES ('La isla del tesoro', 'Robert Louis Stevenson', 1882, 8);
INSERT INTO books (title, author, release_date, stock) VALUES ('Un mundo feliz', 'Aldous Huxley', 1932, 7);
INSERT INTO books (title, author, release_date, stock) VALUES ('El retrato de Dorian Gray', 'Oscar Wilde', 1890, 6);
INSERT INTO books (title, author, release_date, stock) VALUES ('Rayuela', 'Julio Cortázar', 1963, 8);
INSERT INTO books (title, author, release_date, stock) VALUES ('Matadero 5', 'Kurt Vonnegut', 1969, 5);
INSERT INTO books (title, author, release_date, stock) VALUES ('Los miserables', 'Victor Hugo', 1862, 13);
INSERT INTO books (title, author, release_date, stock) VALUES ('La brújula dorada', 'Philip Pullman', 1995, 6);
INSERT INTO books (title, author, release_date, stock) VALUES ('La hoguera de las vanidades', 'Tom Wolfe', 1987, 9);
INSERT INTO books (title, author, release_date, stock) VALUES ('El médico', 'Noah Gordon', 1986, 7);
INSERT INTO books (title, author, release_date, stock) VALUES ('El nombre de la brisa', 'Patrick Rothfuss', 2021, 10);
INSERT INTO books (title, author, release_date, stock) VALUES ('La ciudad de los prodigios', 'Eduardo Mendoza', 1986, 8);
INSERT INTO books (title, author, release_date, stock) VALUES ('Los ojos amarillos de los cocodrilos', 'Katherine Pancol', 2006, 5);
INSERT INTO books (title, author, release_date, stock) VALUES ('El amor en los tiempos del cólera', 'Gabriel García Márquez', 1985, 8);
INSERT INTO books (title, author, release_date, stock) VALUES ('Crónica de una muerte anunciada', 'Gabriel García Márquez', 1981, 3);
INSERT INTO books (title, author, release_date, stock) VALUES ('La hojarasca', 'Gabriel García Márquez', 1955, 2);
INSERT INTO books (title, author, release_date, stock) VALUES ('El Código Da Vinci', 'Dan Brown', 2003, 10);
INSERT INTO books (title, author, release_date, stock) VALUES ('Ángeles y demonios', 'Dan Brown', 2000, 8);
INSERT INTO books (title, author, release_date, stock) VALUES ('Origen', 'Dan Brown', 2017, 6);
INSERT INTO books (title, author, release_date, stock) VALUES ('El otoño del patriarca', 'Gabriel García Márquez', 1975, 6);
INSERT INTO books (title, author, release_date, stock) VALUES ('Noticia de un secuestro', 'Gabriel García Márquez', 1996, 4);
INSERT INTO books (title, author, release_date, stock) VALUES ('Sentido y sensibilidad', 'Jane Austen', 1811, 9);
INSERT INTO books (title, author, release_date, stock) VALUES ('Emma', 'Jane Austen', 1815, 7);
INSERT INTO books (title, author, release_date, stock) VALUES ('Persuasión', 'Jane Austen', 1817, 10);
INSERT INTO books (title, author, release_date, stock) VALUES ('Mansfield Park', 'Jane Austen', 1814, 8);
INSERT INTO books (title, author, release_date, stock) VALUES ('La abadía de Northanger', 'Jane Austen', 1817, 6);
INSERT INTO books (title, author, release_date, stock) VALUES ('La familia Elliot', 'Jane Austen', 1817, 5);
INSERT INTO books (title, author, release_date, stock) VALUES ('Amor y amistad', 'Jane Austen', 1790, 3);
INSERT INTO books (title, author, release_date, stock) VALUES ('La carretera de Wigan Pier', 'George Orwell', 1937, 5);
INSERT INTO books (title, author, release_date, stock) VALUES ('Dentro de la ballena', 'George Orwell', 1940, 3);
INSERT INTO books (title, author, release_date, stock) VALUES ('Un cuarto propio', 'George Orwell', 1941, 7);
INSERT INTO books (title, author, release_date, stock) VALUES ('Disparando al elefante', 'George Orwell', 1950, 4);
INSERT INTO books (title, author, release_date, stock) VALUES ('El camino de Wigan', 'George Orwell', 1937, 6);
INSERT INTO books (title, author, release_date, stock) VALUES ('Londres', 'George Orwell', 1946, 8);
INSERT INTO books (title, author, release_date, stock) VALUES ('El reino de la palabra', 'George Orwell', 1946, 5);
INSERT INTO books (title, author, release_date, stock) VALUES ('Rebelión en la granja', 'George Orwell', 1945, 6);
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('John', 'Doe', 2010, 'johndoe@example.com', '2016-08-21');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Mary', 'Johnson', 2009, 'maryjohnson@example.com', '2017-04-05');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Michael', 'Brown', 2012, 'michaelbrown@example.com', '2018-01-12');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Sarah', 'Clark', 2011, 'sarahclark@example.com', '2019-06-30');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Emily', 'Anderson', 2007, 'emilyanderson@example.com', '2015-10-04');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Robert', 'Jones', 2014, 'robertjones@example.com', '2020-09-19');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Amanda', 'Taylor', 2013, 'amandataylor@example.com', '2018-07-02');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Kevin', 'Harris', 2006, 'kevinharris@example.com', '2014-03-28');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Laura', 'Miller', 2015, 'lauramiller@example.com', '2021-02-14');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Brian', 'Wilson', 2016, 'brianwilson@example.com', '2022-05-07');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Jessica', 'Smithson', 2008, 'jessicasmithson@example.com', '2016-08-09');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Daniel', 'Davis', 2009, 'danieldavis@example.com', '2017-06-18');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Karen', 'Robinson', 2017, 'karenrobinson@example.com', '2023-01-25');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Thomas', 'Evans', 2010, 'thomasevans@example.com', '2018-04-14');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Michelle', 'Garcia', 2011, 'michellegarcia@example.com', '2019-08-03');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Andrew', 'Parker', 2007, 'andrewparker@example.com', '2015-11-29');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Natalie', 'Carter', 2013, 'nataliecarter@example.com', '2020-10-12');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Jason', 'Cook', 2014, 'jasoncook@example.com', '2021-06-02');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Lisa', 'Baker', 2012, 'lisabaker@example.com', '2019-01-09');
INSERT INTO users (name, last_name, member_since, email, create_at) VALUES ('Paul', 'Lee', 2015, 'paullee@example.com', '2022-08-22');

